### ISSUE TITLE
Невозможно развернуть проект

### ISSUE THREAD

**Issue by VegasChickiChicki** [yarvod/popso_news#1]
На 9 пункте, после авторизации в админке выдает 500 код. В контейнере "popso-news-backend" появляется ошибка:

2023-03-09 17:52:32,496 ERROR django.request [/usr/local/lib/python3.9/site-packages/django/utils/log.py:224] Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django_redis/cache.py", line 137, in has_key
    return self.client.has_key(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django_redis/client/default.py", line 666, in has_key
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error -3 connecting to reids:6379. Temporary failure in name resolution.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 414, in login
    return LoginView.as_view(**defaults)(request)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/views.py", line 92, in form_valid
    auth_login(self.request, form.get_user())
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 111, in login
    request.session.cycle_key()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 344, in cycle_key
    self.create()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/cache.py", line 43, in create
    self._session_key = self._get_new_session_key()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 196, in _get_new_session_key
    if not self.exists(session_key):
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/cache.py", line 70, in exists
    return bool(session_key) and (self.cache_key_prefix + session_key) in self._cache
  File "/usr/local/lib/python3.9/site-packages/django/core/cache/backends/base.py", line 212, in __contains__
    return self.has_key(key)
  File "/usr/local/lib/python3.9/site-packages/django_redis/cache.py", line 38, in _decorator
    raise e.__cause__
  File "/usr/local/lib/python3.9/site-packages/django_redis/client/default.py", line 664, in has_key
    return client.exists(key) == 1
  File "/usr/local/lib/python3.9/site-packages/redis/commands/core.py", line 1606, in exists
    return self.execute_command("EXISTS", *names)
  File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1232, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 1383, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 615, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to reids:6379. Temporary failure in name resolution.

содержимое .env файла(API_ID и API_HASH скрыты):

API_ID=,,,
API_HASH=...

POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
DB_HOST=host.docker.internal
DB_PORT=5432

REDIS_HOST=reids
REDIS_PORT=6379
REDIS_PASSWORD=reids

**Comment by VegasChickiChicki** [comment]
Моя ошибка, не правильно записан значение переменной REDIS_HOST в env файле.
